'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unknown='Not listed', value=v=>v===null||v===undefined||v===''?unknown:typeof v==='boolean'?(v?'Yes':'No'):v;
const money=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(v)+' GEL';
let data=window.HOUSE_HUNT, properties=[], view='all', selected=new Set(), saved={favorites:[],hidden:[]};
try{const s=JSON.parse(localStorage.getItem('house-hunt-v1'));if(s&&Array.isArray(s.favorites)&&Array.isArray(s.hidden))saved={favorites:s.favorites.map(String),hidden:s.hidden.map(String)}}catch{}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,3500)}
function persist(){try{localStorage.setItem('house-hunt-v1',JSON.stringify(saved));return true}catch{toast('Browser storage is unavailable. Changes last for this session only.');return false}}
function safeUrl(url){try{const u=new URL(url);return u.protocol==='https:'?u.href:'#'}catch{return '#'}}
function imageUrl(url){return /^data\/images\/[\w.-]+$/.test(url||'')?url:safeUrl(url)}
const floor=p=>p.floor===null?unknown:`${p.floor} / ${p.total_floors??'?'}`;
const date=p=>p.listing_date?new Date(p.listing_date).toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'Asia/Tbilisi'}):unknown;
function facts(p){const good=[],bad=[...(p.considerations||[])];if(p.condition==='Newly renovated')good.push('Newly renovated (listing states)');if(p.furniture===true)good.push('Furniture included (listing states)');if(p.heating)good.push(p.heating);if(p.parking)good.push(p.parking);if(p.balcony)good.push('Balcony listed');if(p.price<900)good.push(`${money(1000-p.price)} below your maximum`);if(p.advance_months)bad.push(`${p.advance_months} months’ rent payable in advance (listing states)`);if(p.floor===1)bad.push('First floor — consider privacy when viewing');if(p.floor===p.total_floors)bad.push('Top floor — check roof condition when viewing');if(p.original_currency==='USD')bad.push('USD asking rent: GEL equivalent may change');return {good,bad}}
function card(p){const favorite=saved.favorites.includes(p.id),hidden=saved.hidden.includes(p.id);const features=[p.condition,p.furniture===true?'Furnished':null,p.heating,p.balcony?'Balcony':null].filter(Boolean).slice(0,3);return `<article class="card" data-id="${esc(p.id)}"><div class="photo-wrap"><button class="photo-open" data-action="details" aria-label="View ${esc(p.address)}"><img src="${esc(imageUrl(p.main_image))}" alt="${esc(p.neighborhood)} apartment, listing ${esc(p.id)}" loading="lazy"></button><button class="favorite" data-action="favorite" aria-label="${favorite?'Unfavorite':'Favorite'} ${esc(p.id)}" aria-pressed="${favorite}">${favorite?'♥':'♡'}</button><span class="badge">${p.price>=900?'WITHIN PREFERRED BUDGET':'BELOW PREFERRED BUDGET'}</span></div><div class="card-body"><div class="price">${p.price.toLocaleString('en-US')} ₾ <small>/ month</small></div><h2>${esc(p.neighborhood)}</h2><p class="address" title="${esc(p.address)}">${esc(p.address||unknown)}</p><div class="specs"><span>${p.size} m²</span><span>${esc(value(p.rooms))} ${p.rooms===1?'room':'rooms'}</span><span>Floor ${esc(floor(p))}</span></div><div class="features">${features.map(f=>`<span class="feature">${esc(f)}</span>`).join('')}</div><div class="card-actions"><label class="compare-check"><input type="checkbox" data-action="compare" aria-label="Compare ${esc(p.id)}" ${selected.has(p.id)?'checked':''}>Compare</label><button data-action="hide" title="Hidden listings stay excluded after daily updates on this browser">${hidden?'Restore':'Hide'}</button><a href="${esc(safeUrl(p.url))}" target="_blank" rel="noopener noreferrer">myhome.ge ↗</a></div><div class="card-meta"><span>${date(p)} · #${esc(p.id)}</span><button class="quiet" data-action="details">Details & photos</button></div></div></article>`}
function render(){let list=properties.filter(p=>view==='hidden'?saved.hidden.includes(p.id):!saved.hidden.includes(p.id)&&(view!=='favorites'||saved.favorites.includes(p.id)));const district=$('#district').value;if(district)list=list.filter(p=>p.district_groups.includes(district));const sorting={'price-asc':(a,b)=>a.price-b.price,'price-desc':(a,b)=>b.price-a.price,'size-desc':(a,b)=>b.size-a.size,'size-asc':(a,b)=>a.size-b.size,'newest':(a,b)=>(Date.parse(b.listing_date)||0)-(Date.parse(a.listing_date)||0)};list.sort(sorting[$('#sort').value]);$('#grid').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h2>${view==='favorites'?'Your shortlist starts here.':view==='hidden'?'No hidden homes here.':'No saved matches in this district.'}</h2><p>${view==='favorites'?'Tap a heart on a home to save it.':'Try another district or view. This is a limited snapshot, not every available rental.'}</p></div>`;$('#allCount').textContent=properties.filter(p=>!saved.hidden.includes(p.id)).length;$('#favCount').textContent=properties.filter(p=>saved.favorites.includes(p.id)&&!saved.hidden.includes(p.id)).length;$('#hiddenCount').textContent=properties.filter(p=>saved.hidden.includes(p.id)).length;$('#resultCount').textContent=`${list.length} ${list.length===1?'home':'homes'}`;document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',b.dataset.view===view)});$('#compareBar').hidden=!selected.size;$('#selectedCount').textContent=`${selected.size} of 4 homes selected`;$('#openCompare').disabled=selected.size<2;document.querySelectorAll('.photo-wrap img').forEach(img=>img.onerror=()=>{img.style.display='none';img.parentElement.textContent='Photo unavailable · open original listing'})}
function openModal(title,html){$('#modalTitle').textContent=title;$('#modalContent').innerHTML=html;$('#modal').showModal()}
function detail(p){const fields={Rent:money(p.price)+' / month',District:p.district,Neighborhood:p.neighborhood,Address:p.address,Size:p.size+' m²',Rooms:p.rooms,Bedrooms:p.bedrooms,Floor:floor(p),Condition:p.condition,Furniture:p.furniture,Heating:p.heating,'Air conditioning':p.air_conditioning,Balcony:p.balcony,Parking:p.parking,'Listing date':date(p),'Listing ID':p.id,'Last checked':p.last_checked_at||p.retrieved_at};openModal(p.neighborhood,`<div class="gallery">${p.images.map((src,i)=>`<img src="${esc(imageUrl(src))}" alt="Listing ${esc(p.id)}, photo ${i+1}" loading="lazy">`).join('')}</div><a href="${esc(safeUrl(p.url))}" target="_blank" rel="noopener noreferrer">View original listing on myhome.ge ↗</a><dl class="detail-grid">${Object.entries(fields).map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(value(v))}</dd></div>`).join('')}</dl><div data-id="${esc(p.id)}"><button class="primary" data-action="hide">${saved.hidden.includes(p.id)?'Restore listing':'Hide this listing'}</button></div><h3>Original description</h3><p class="description" lang="ka">${esc(p.description||unknown)}</p><p class="data-note">${esc(p.condition_review)} ${esc(p.photos_reviewed)}${p.listing_date?' Listing date may reflect a renewed advertisement.':''}</p>`)}
function compare(){const ps=properties.filter(p=>selected.has(p.id));const rows=[['Rent',p=>money(p.price)+' / month'],['Location',p=>p.neighborhood+' · '+p.address],['Size',p=>p.size+' m²'],['Price per m²',p=>money(Math.round(p.price/p.size*100)/100)+' / m²'],['Rooms',p=>value(p.rooms)],['Bedrooms',p=>value(p.bedrooms)],['Floor',floor],['Condition',p=>value(p.condition)],['Heating',p=>value(p.heating)],['Furniture',p=>value(p.furniture)],['Parking',p=>value(p.parking)],['Air conditioning',p=>value(p.air_conditioning)],['Balcony',p=>value(p.balcony)]];openModal('Compare your homes',`<p class="data-note">Facts come from the listings. Viewing considerations are labeled; missing amenities are not assumed absent.</p><div class="table-wrap"><table><thead><tr><th>At a glance</th>${ps.map(p=>`<th><img class="table-img" src="${esc(imageUrl(p.main_image))}" alt="${esc(p.neighborhood)}">${esc(p.neighborhood)}<br>#${esc(p.id)}</th>`).join('')}</tr></thead><tbody>${rows.map(([k,f])=>`<tr><th scope="row">${k}</th>${ps.map(p=>`<td>${esc(f(p))}</td>`).join('')}</tr>`).join('')}${[['Advantages','good'],['Disadvantages / considerations','bad']].map(([title,key])=>`<tr><th scope="row">${title}</th>${ps.map(p=>{const f=facts(p)[key];return `<td>${f.length?'<ul>'+f.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>':'None established from available data'}</td>`}).join('')}</tr>`).join('')}<tr><th scope="row">Original listing</th>${ps.map(p=>`<td><a href="${esc(safeUrl(p.url))}" target="_blank" rel="noopener noreferrer">Open myhome.ge ↗</a></td>`).join('')}</tr></tbody></table></div>`)}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){view=v.dataset.view;render();return}const b=e.target.closest('[data-action]');if(!b||b.dataset.action==='compare')return;const p=properties.find(p=>p.id===b.closest('[data-id]').dataset.id);if(b.dataset.action==='details')return detail(p);const key=b.dataset.action==='favorite'?'favorites':'hidden';saved[key]=saved[key].includes(p.id)?saved[key].filter(id=>id!==p.id):[...saved[key],p.id];if(key==='hidden'){selected.delete(p.id);if($('#modal').open)$('#modal').close()}const stored=persist();render();if(key==='hidden'&&stored)toast(saved.hidden.includes(p.id)?'Hidden. This listing will stay out of your list, including after daily updates.':'Listing restored to your list.')});
$('#grid').addEventListener('change',e=>{if(e.target.dataset.action!=='compare')return;const id=e.target.closest('[data-id]').dataset.id;if(e.target.checked&&selected.size===4){e.target.checked=false;toast('Compare up to 4 homes at a time.');return}e.target.checked?selected.add(id):selected.delete(id);render()});
$('#district').addEventListener('change',render);$('#sort').addEventListener('change',render);$('#clearCompare').onclick=()=>{selected.clear();render()};$('#openCompare').onclick=compare;$('#closeModal').onclick=()=>$('#modal').close();
async function init(){try{if(location.protocol!=='file:'){const r=await fetch('data/properties.json?t='+Date.now(),{cache:'no-store'});if(r.ok)data=await r.json()}if(!data||!Array.isArray(data.properties))throw Error('No saved dataset');properties=data.properties.filter(p=>Number.isFinite(p.price)&&p.price>0&&p.price<=1000&&p.currency==='GEL'&&p.size>=38&&p.transaction==='rent_monthly'&&p.property_type==='apartment'&&p.screening==='include');$('#sourceNote').textContent=`Snapshot saved ${new Date(data.retrieved_at).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})} · ${data.method_label} · Availability not confirmed`;$('#coverage').textContent=data.coverage_note;const status=data.refresh_status;$('#refreshStatus').textContent=status?`Last attempt: ${new Date(status.attempted_at).toLocaleString('en-GB',{timeZone:'Asia/Tbilisi'})} (Tbilisi) | ${status.status==='success'?'Collection completed':('REFRESH FAILED - showing retained listings. '+(status.error||''))}`:'No automated refresh completed yet.';render()}catch{ $('#sourceNote').textContent='The saved listings could not be loaded. Keep the data folder beside index.html and reopen the page.';$('#grid').innerHTML='<div class="empty"><h2>Saved data unavailable</h2><p>See README.md for recovery steps.</p></div>'}}
init();
if(location.protocol==='https:'||location.protocol==='http:'){
  setInterval(()=>{if(!document.hidden)init()},5*60*1000);
  document.addEventListener('visibilitychange',()=>{if(!document.hidden)init()});
}

window.addEventListener('storage',e=>{if(e.key!=='house-hunt-v1')return;try{const next=JSON.parse(e.newValue);if(!next||!Array.isArray(next.favorites)||!Array.isArray(next.hidden))return;saved={favorites:next.favorites.map(String),hidden:next.hidden.map(String)};for(const id of selected)if(saved.hidden.includes(id))selected.delete(id);render()}catch{}});
